#!/usr/bin/env ruby

if ENV['RAILS_ENV'] == 'test' && ENV["COVERAGE"]
  require 'simplecov'

  if ENV["COVERALLS"]
    require 'coveralls'
    SimpleCov.formatter = SimpleCov::Formatter::MultiFormatter[
      SimpleCov::Formatter::HTMLFormatter,
      Coveralls::SimpleCov::Formatter
    ]
  end

  SimpleCov.start 'rails' do
    add_filter 'vendor'
  end
end


# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require 'rails/commands'
